name: Build

on:
  workflow_dispatch:
  push:
    tags:
    - 'v*.*.*'

jobs:

  build:
    name: Build the Docker image
    runs-on: ubuntu-latest

    env:
      DOCKER_BUILDKIT: 1
      METACALL_GUIX_VERSION: 1.3.0
      METACALL_GUIX_ARCH: x86_64

    steps:
      - name: Check out the repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Docker Setup BuildX
        uses: docker/setup-buildx-action@v2.0.0
        with:
          version: v0.5.1

      - name: Verify Docker BuildX Version
        run: docker buildx version
      
      - name: Create a new builder instance
        run: docker buildx create --use --name insecure-builder --buildkitd-flags '--allow-insecure-entitlement security.insecure'
      
      # - name: Authenticate to Docker registry
      #   uses: docker/login-action@v2
      #   with:
      #     username: ${{ secrets.DOCKER_USERNAME }}
      #     password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push image
        run: docker buildx build -t metacall/guix --allow security.insecure --build-arg METACALL_GUIX_VERSION="$METACALL_GUIX_VERSION" --build-arg METACALL_GUIX_ARCH="$METACALL_GUIX_ARCH" .
